default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5

development:
    <<: *default
    database: language_app_development

test:
    <<: *default
    database: language_app_test

production:
    <<: *default
    database: language_app_production
